

Category and Product Collections
<br/>
---
<br/>
Singlepage approach with deeplink fun ( ExtJS, React, VueJS )
<br/>
<br/>

<?php print $block->getCart();		 					?>
<br/>
<br/>

<?php print $block->getCategories(); 					?>
<br/>
<br/>

<br/>
Might not need all the products at once since the product lists is linked to the selected categories each

<?php print $block->getProducts(); 						?>
<br/>
<br/>



<div id="resp"></div>
<script type="text/x-magento-init">
{
    "*": {
        "Snoggie_Lurkemurk/catalog": {}
    }
}
</script>

