

Category collection, product collection
<br/>
Cart commands
<br/>
Customer commands
<br/>
---
<br/>
Singlepage approach with deeplink fun ( ExtJS, React, VueJS )
<br/>
<br/>
<br/>

<?php print $block->getCart();		 					?>
<br/>
<br/>

<?php print $block->getCategories(); 					?>
<br/>
<br/>

Might not need all the products since the product lists is linked to the selected categories each
<br/>
<br/>

<?php print $block->getProducts(); 						?>
<br/>
<br/>



<div id="resp"></div>
<script type="text/x-magento-init">
{
    "*": {
        "Snoggie_Lurkemurk/main": {}
    }
}
</script>

