

Category collection, product collection
<br/>
Cart commands
<br/>
Customer commands
<br/>
---
<br/>
Singlepage approach with deeplink fun ( ExtJS, React, VueJS )
<br/>
<br/>
The objectives was a shop as for a shop for targets that a client would! have bought in some other shops as for to gather the goods he or she would have spent money on but than he and she did not like i almost did buy this here https://www.thegreenhead.com/imgs/xl/beardski-bearded-ski-mask-xl.jpg a year ago but than i would not and than this is savings of 50 dollars know? 
<br/>
<br/>
<br/>

<?php print $block->getCart();		 					?>
<br/>
<br/>

<?php print $block->getCategories(); 					?>
<br/>
<br/>

Might not need all the products since the product lists is linked to the selected categories each
<br/>
<br/>

<?php print $block->getProducts(); 						?>
<br/>
<br/>



<div id="resp"></div>
<script type="text/x-magento-init">
{
    "*": {
        "Snoggie_Lurkemurk/main": {}
    }
}
</script>

